# Generated by Django 6.0.3 on 2026-03-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="a", max_length=200),
            preserve_default=False,
        ),
    ]
