# Generated by Django 6.0.3 on 2026-03-10 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_author_ip_post_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_datetime"]},
        ),
    ]
